import pandas as pd
import sqlite3
from langchain.agents import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from dotenv import load_dotenv, find_dotenv
import os
import openai
from langchain.agents.agent_types import AgentType
from langchain.sql_database import SQLDatabase
from langchain.llms.openai import OpenAI
import numpy as np 
from pandasai import PandasAI 
from pandasai import SmartDataframe
from pandasai.llm.openai import OpenAI

_=load_dotenv(find_dotenv())
openai.api_key = os.environ["OPENAI_API_KEY"]

#Connection to database
connection = sqlite3.connect('rr.db') # type: ignore
cursor = connection.cursor()

#Create a products table - 5
command1 = """CREATE TABLE IF NOT EXISTS
offers(
    id INT PRIMARY KEY,
    credit_card_name VARCHAR(255),
    category VARCHAR(255),
    minimum_booking_amount VARCHAR(50),
    discount VARCHAR(50),
    expiry_date VARCHAR(50),
    coupon_code VARCHAR(50),
    website_link VARCHAR(255),
    information TEXT,
    terms_and_conditions TEXT
)"""

cursor.execute(command1)

cursor.execute("INSERT OR IGNORE INTO offers VALUES(1, 'ICICI Bank Credit Cards', 'Domestic Flights', 'Rs. 5,000', 'Flat 12% off up to Rs. 2,023*', '30th Sept, 2023', 'ICICIEMT', 'https://www.example.com/book-domestic-flight', 'How to Avail the Offer:\n- Use promo code ICICIEMT during booking.\n- Valid only on Saturdays until 30th Sept''23.\n- Valid for all users with ICICI Bank Credit Cards.\n- Applicable to online confirmed bookings on EaseMyTrip website and app.\n- Minimum transaction value: INR 5,000 for domestic flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to ICICI Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(2, 'ICICI Bank Credit Cards', 'International Flights', 'Rs. 10,000', 'Flat 10% off up to Rs. 5,000*', '30th Sept, 2023', 'ICICIEMT', 'https://www.example.com/book-international-flight', 'How to Avail the Offer:\n- Use promo code ICICIEMT during booking.\n- Valid only on Saturdays until 30th Sept''23.\n- Valid for all users with ICICI Bank Credit Cards.\n- Applicable to online confirmed bookings on EaseMyTrip website and app.\n- Minimum transaction value: INR 10,000 for international flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to ICICI Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(3, 'HDFC Bank Credit Cards', 'International Flights', 'Rs. 7,500', 'Flat 15% off up to Rs. 4,000*', '15th Oct, 2023', 'HDFCFIT', 'https://www.travelworld.com/book-international-flight', 'How to Avail the Offer:\n- Use promo code HDFCFIT during booking.\n- Valid only on Sundays until 15th Oct''23.\n- Valid for all users with HDFC Bank Credit Cards.\n- Applicable to online confirmed bookings on Travel World website and app.\n- Minimum transaction value: INR 7,500 for international flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to HDFC Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(4, 'Axis Bank Credit Cards', 'Domestic Flights', 'Rs. 4,000', 'Flat 10% off up to Rs. 2,000*', '30th Nov, 2023', 'AXISDOM', 'https://www.travelsmart.com/book-domestic-flight', 'How to Avail the Offer:\n- Use promo code AXISDOM during booking.\n- Valid only on Mondays until 30th Nov''23.\n- Valid for all users with Axis Bank Credit Cards.\n- Applicable to online confirmed bookings on Travel Smart website and app.\n- Minimum transaction value: INR 4,000 for domestic flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to Axis Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(5, 'CitiBank Credit Cards', 'International Flights', 'Rs. 8,000', 'Flat 12% off up to Rs. 3,500*', '15th Nov, 2023', 'CITIFLY', 'https://www.exploreplaces.com/book-international-flight', 'How to Avail the Offer:\n- Use promo code CITIFLY during booking.\n- Valid only on Tuesdays until 15th Nov''23.\n- Valid for all users with CitiBank Credit Cards.\n- Applicable to online confirmed bookings on Explore Places website and app.\n- Minimum transaction value: INR 8,000 for international flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to CitiBank Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(6, 'SBI Credit Cards', 'Domestic Flights', 'Rs. 6,000', 'Flat 10% off up to Rs. 2,500*', '20th Oct, 2023', 'SBIFLY', 'https://www.travelzone.com/book-domestic-flight', 'How to Avail the Offer:\n- Use promo code SBIFLY during booking.\n- Valid only on Wednesdays until 20th Oct''23.\n- Valid for all users with SBI Credit Cards.\n- Applicable to online confirmed bookings on Travel Zone website and app.\n- Minimum transaction value: INR 6,000 for domestic flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to SBI Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(7, 'HDFC Bank Credit Cards', 'Domestic Flights', 'Rs. 5,500', 'Flat 12% off up to Rs. 2,200*', '25th Nov, 2023', 'HDFCFLY', 'https://www.flyworld.com/book-domestic-flight', 'How to Avail the Offer:\n- Use promo code HDFCFLY during booking.\n- Valid only on Fridays until 25th Nov''23.\n- Valid for all users with HDFC Bank Credit Cards.\n- Applicable to online confirmed bookings on Fly World website and app.\n- Minimum transaction value: INR 5,500 for domestic flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to HDFC Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(8, 'Axis Bank Credit Cards', 'International Flights', 'Rs. 10,000', 'Flat 10% off up to Rs. 5,000*', '5th Dec, 2023', 'AXISGLOBE', 'https://www.globetrek.com/book-international-flight', 'How to Avail the Offer:\n- Use promo code AXISGLOBE during booking.\n- Valid only on Tuesdays until 5th Dec''23.\n- Valid for all users with Axis Bank Credit Cards.\n- Applicable to online confirmed bookings on Globe Trek website and app.\n- Minimum transaction value: INR 10,000 for international flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to Axis Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(9, 'CitiBank Credit Cards', 'Domestic Flights', 'Rs. 6,500', 'Flat 10% off up to Rs. 3,000*', '10th Nov, 2023', 'CITIFLYNOW', 'https://www.airtravels.com/book-domestic-flight', 'How to Avail the Offer:\n- Use promo code CITIFLYNOW during booking.\n- Valid only on Wednesdays until 10th Nov''23.\n- Valid for all users with CitiBank Credit Cards.\n- Applicable to online confirmed bookings on Air Travels website and app.\n- Minimum transaction value: INR 6,500 for domestic flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to CitiBank Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(10, 'SBI Credit Cards', 'International Flights', 'Rs. 8,500', 'Flat 12% off up to Rs. 4,000*', '20th Dec, 2023', 'SBIWORLD', 'https://www.worldwanderer.com/book-international-flight', 'How to Avail the Offer:\n- Use promo code SBIWORLD during booking.\n- Valid only on Thursdays until 20th Dec''23.\n- Valid for all users with SBI Credit Cards.\n- Applicable to online confirmed bookings on World Wanderer website and app.\n- Minimum transaction value: INR 8,500 for international flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to SBI Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(11, 'ICICI Bank Credit Cards', 'Domestic Flights', 'Rs. 4,500', 'Flat 10% off up to Rs. 2,000*', '5th Nov, 2023', 'ICICISAVE', 'https://www.travelhub.com/book-domestic-flight', 'How to Avail the Offer:\n- Use promo code ICICISAVE during booking.\n- Valid only on Mondays until 5th Nov''23.\n- Valid for all users with ICICI Bank Credit Cards.\n- Applicable to online confirmed bookings on Travel Hub website and app.\n- Minimum transaction value: INR 4,500 for domestic flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to ICICI Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(12, 'HDFC Bank Credit Cards', 'International Flights', 'Rs. 9,000', 'Flat 15% off up to Rs. 4,500*', '15th Dec, 2023', 'HDFCGLOBE', 'https://www.globetour.com/book-international-flight', 'How to Avail the Offer:\n- Use promo code HDFCGLOBE during booking.\n- Valid only on Fridays until 15th Dec''23.\n- Valid for all users with HDFC Bank Credit Cards.\n- Applicable to online confirmed bookings on Globe Tour website and app.\n- Minimum transaction value: INR 9,000 for international flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to HDFC Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(13, 'YES Bank Credit Cards', 'Domestic Flights', 'Rs. 5,000', 'Flat 12% off up to Rs. 2,400*', '10th Nov, 2023', 'YESFLY', 'https://www.travelup.com/book-domestic-flight', 'How to Avail the Offer:\n- Use promo code YESFLY during booking.\n- Valid only on Saturdays until 10th Nov''23.\n- Valid for all users with YES Bank Credit Cards.\n- Applicable to online confirmed bookings on Travel Up website and app.\n- Minimum transaction value: INR 5,000 for domestic flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to YES Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(14, 'CitiBank Credit Cards', 'International Flights', 'Rs. 10,000', 'Flat 10% off up to Rs. 5,000*', '20th Dec, 2023', 'CITIEXPLORE', 'https://www.exploretheworld.com/book-international-flight', 'How to Avail the Offer:\n- Use promo code CITIEXPLORE during booking.\n- Valid only on Sundays until 20th Dec''23.\n- Valid for all users with CitiBank Credit Cards.\n- Applicable to online confirmed bookings on Explore the World website and app.\n- Minimum transaction value: INR 10,000 for international flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to CitiBank Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(15, 'Bank of Baroda Credit Cards', 'Domestic Flights', 'Rs. 7,500', 'Flat 15% off up to Rs. 3,500*', '5th Dec, 2023', 'BOBDOM', 'https://www.flyeasy.com/book-domestic-flight', 'How to Avail the Offer:\n- Use promo code BOBDOM during booking.\n- Valid only on Mondays until 5th Dec''23.\n- Valid for all users with BOB Credit Cards.\n- Applicable to online confirmed bookings on Fly Easy website and app.\n- Minimum transaction value: INR 7,500 for domestic flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to BOB Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(16, 'PNB Bank Credit Cards', 'International Flights', 'Rs. 8,500', 'Flat 12% off up to Rs. 4,000*', '10th Nov, 2023', 'PNBTRAVEL', 'https://www.traveluniverse.com/book-international-flight', 'How to Avail the Offer:\n- Use promo code PNBTRAVEL during booking.\n- Valid only on Tuesdays until 10th Nov''23.\n- Valid for all users with PNB Bank Credit Cards.\n- Applicable to online confirmed bookings on Travel Universe website and app.\n- Minimum transaction value: INR 8,500 for international flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to ICICI Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(17, 'AU Bank Credit Cards', 'Domestic Flights', 'Rs. 6,500', 'Flat 10% off up to Rs. 3,000*', '20th Dec, 2023', 'AUSKY', 'https://www.skyscapes.com/book-domestic-flight', 'How to Avail the Offer:\n- Use promo code AUSKY during booking.\n- Valid only on Wednesdays until 20th Dec''23.\n- Valid for all users with AU Bank Credit Cards.\n- Applicable to online confirmed bookings on Sky Scapes website and app.\n- Minimum transaction value: INR 6,500 for domestic flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to RBL Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(18, 'RBL Bank Credit Cards', 'International Flights', 'Rs. 9,000', 'Flat 15% off up to Rs. 4,500*', '15th Nov, 2023', 'RBLWINGS', 'https://www.wingstravels.com/book-international-flight', 'How to Avail the Offer:\n- Use promo code RBLWINGS during booking.\n- Valid only on Thursdays until 15th Nov''23.\n- Valid for all users with RBL Bank Credit Cards.\n- Applicable to online confirmed bookings on Wings Travels website and app.\n- Minimum transaction value: INR 9,000 for international flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to RBL Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(19, 'Standard Chartered Bank Credit Cards', 'Domestic Flights', 'Rs. 7,000', 'Flat 12% off up to Rs. 3,000*', '25th Oct, 2023', 'STBFLIER', 'https://www.flyhigh.com/book-domestic-flight', 'How to Avail the Offer:\n- Use promo code STBFLIER during booking.\n- Valid only on Fridays until 25th Oct''23.\n- Valid for all users with Standard Chartered Bank Credit Cards.\n- Applicable to online confirmed bookings on Fly High website and app.\n- Minimum transaction value: INR 7,000 for domestic flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to Standard Chartered Bank Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(20, 'HSBC Credit Cards', 'International Flights', 'Rs. 10,000', 'Flat 10% off up to Rs. 5,000*', '10th Oct, 2023', 'HSBCEXPLORE', 'https://www.explorenow.com/book-international-flight', 'How to Avail the Offer:\n- Use promo code HSBCEXPLORE during booking.\n- Valid only on Saturdays until 10th Oct''23.\n- Valid for all users with HSBC Credit Cards.\n- Applicable to online confirmed bookings on Explore Now website and app.\n- Minimum transaction value: INR 10,000 for international flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to HSBC Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(21, 'Indusland Bank Credit Cards', 'Domestic Flights', 'Rs. 8,000', 'Flat 15% off up to Rs. 4,000*', '30th Dec, 2023', 'INDUSSKY', 'https://www.skytrips.com/book-domestic-flight', 'How to Avail the Offer:\n- Use promo code INDUSSKY during booking.\n- Valid only on Sundays until 30th Dec''23.\n- Valid for all users with Indusland Bank Credit Cards.\n- Applicable to online confirmed bookings on Sky Trips website and app.\n- Minimum transaction value: INR 8,000 for domestic flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to Indusland Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute("INSERT OR IGNORE INTO offers VALUES(22, 'Niyo global Credit Cards', 'International Flights', 'Rs. 7,500', 'Flat 12% off up to Rs. 3,500*', '25th Oct, 2023', 'NIYOTRAVEL', 'https://www.travelconnect.com/book-international-flight', 'How to Avail the Offer:\n- Use promo code NIYOTRAVEL during booking.\n- Valid only on Mondays until 25th Oct''23.\n- Valid for all users with NIYO global Credit Cards.\n- Applicable to online confirmed bookings on Travel Connect website and app.\n- Minimum transaction value: INR 7,500 for international flights.\n- Convenience fee applies as per the applicability.\n- Offer valid once per card per product per month.\n- Offer not applicable to HDFC Amazon Co-Brand Card.\n- Changes in flights and dates allowed with fees and fare difference.\n- Changes in names are not allowed.', 'In case of misuse or abuse, EaseMyTrip reserves the right to deny the offer.\nEaseMyTrip''s standard booking and privacy policy on www.EaseMyTrip.com applies.\nDisputes will be resolved in the Courts of New Delhi.\nEaseMyTrip reserves the right to modify or withdraw the offer without notice.\nEaseMyTrip is not liable for any loss or damage due to force majeure.')")

cursor.execute('SELECT * FROM offers')

# Commit the changes and close the connection
connection.commit()
#conn.close()

print("Data added to all tables successfully!\n")

# Connect to an existing database file
conn = sqlite3.connect('rr.db')

# Create a cursor object to execute SQL queries
cursor = conn.cursor()

# Execute a SELECT query
cursor.execute('SELECT * FROM offers')

# Fetch the query results
rows = cursor.fetchall()

print("Table Data: ",rows)

# define the SQL query
query = "SELECT * FROM offers"

# execute the query and return the results as a Pandas dataframe
df = pd.read_sql(query, conn)

print("The Dataframe contains: \n", df)

# Assuming df is your DataFrame
column_names = df.columns.tolist()

# Print or use the column names as needed
print("Column names: \n",column_names)

#initiating Pandas AI
llm = OpenAI(api_token=openai.api_key) 
pandas_ai = PandasAI(llm, conversational=False)

sdf = SmartDataframe(df, config={"llm": llm, "verbose": False})

if sdf is not None:
    print("Sdf contains same data as df ! \n")

# finding index of a row using value of a column 
response = sdf.chat("flight offers on SBI") 

print("The answer to your question is: \n", response)

